server.port=8086
spring.application.name=dormitory-service

# H2 Database
spring.datasource.url=jdbc:h2:mem:dormitory_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# External Services
student-service.url=http://localhost:8081
